version: '3.9'
services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 45s
    volumes:
      - ./database:/var/lib/postgresql/data

  flask-twitter:  
    build: ./twitter
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "80:80"
    
volumes:
  database: